JobNames = [
    "periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-aws-ovn",
    "periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-aws-ovn-csi",
    "periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-azure",
    "periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-metal-ovn",
    "periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-metal-ovn-disconnected",
    "periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-aws-ovn",
    "periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-aws-ovn-csi",
    "periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-kubevirt-azure",
    "periodic-ci-openshift-hypershift-release-4.16-periodics-mce-e2e-kubevirt-metal-ovn",
    "periodic-ci-openshift-hypershift-release-4.16-periodics-mce-e2e-kubevirt-metal-ovn-disconnected",
    "periodic-ci-openshift-hypershift-release-4.16-periodics-mce-e2e-kubevirt-metal-ovn-multinet",
    "periodic-ci-openshift-hypershift-release-4.16-periodics-mce-e2e-kubevirt-metal-ovn-multinet-default-net",
    "periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-aws-ovn",
    "periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-aws-ovn-csi",
    "periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-azure",
    "periodic-ci-openshift-hypershift-release-4.15-periodics-mce-e2e-kubevirt-metal-ovn",
    "periodic-ci-openshift-hypershift-release-4.15-periodics-mce-e2e-kubevirt-metal-ovn-disconnected",
    "periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-aws-csi",
    "periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-aws-ovn",
    "periodic-ci-openshift-hypershift-release-4.14-periodics-mce-e2e-kubevirt-metal-mce-disconnected",
    "periodic-ci-openshift-hypershift-release-4.14-periodics-mce-e2e-kubevirt-metal-ovn",

]