name: Prow Summarizer Bot
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:
jobs:
  override:
    name: Summarize prow jobs from the specified period and post on a slack channel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Collect jobs results, aggragate and post
        run: python main.py
        env:
          DELTA_TIME_HOURS: ${{ vars.DELTA_TIME_HOURS }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
